### PR TITLE
Fix #29

### LINKED ISSUE #29: std::logic_error when building using nix
I tried to package ekam using nix:

https://github.com/zenhack/ekam-nix

But got an error in the second stage of the build. The full log is below. It's possible Nix is doing some kind of sandboxing that is interacting badly with something ekam is trying to do; I'm a little fuzzy on the details of both. But throwing `std::logic_error` looks like a bug in ekam to me.

The nix build script isn't doing anything funny; the only novel bit is that it downloads and links the capnproto source itself, since nix builds don't have network access.

(I'd meant to report this much sooner, but got distracted...)

```
these derivations will be built:
  /nix/store/v9g3kpv513mz21qj955n4l6l9sihsnfg-ekam.drv
building '/nix/store/v9g3kpv513mz21qj955n4l6l9sihsnfg-ekam.drv'...
==== compiling bootstrap ekam ====
g++ -Isrc -std=c++14 src/base/sha256.cpp src/base/Promise.cpp src/base/OwnedPtr.cpp src/base/Hash.cpp src/base/Debug.cpp src/os/Subprocess.cpp src/os/Socket.cpp src/os/OsHandle.cpp src/os/File.cpp src/os/EventManager.cpp src/os/EventGroup.cpp src/os/EpollEventManager.cpp src/os/DiskFile.cpp src/os/ByteStream.cpp src/ekam/initNetworkDashboardStub.cpp src/ekam/ekam.cpp src/ekam/Tag.cpp src/ekam/SimpleDashboard.cpp src/ekam/MuxDashboard.cpp src/ekam/ExecPluginActionFactory.cpp src/ekam/Driver.cpp src/ekam/Dashboard.cpp src/ekam/CppActionFactory.cpp src/ekam/ConsoleDashboard.cpp src/ekam/ActionUtil.cpp src/ekam/Action.cpp -pthread -o bin/ekam-bootstrap
==== building ekam with ekam ====
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
  learn: ekam/rules/compile.ekam-rule
...(more)...
...(more)...
  learn: capnp/capnpc.ekam-rule
...(more)...
...(more)...
  learn: ekam/rules/proto.ekam-rule
...(more)...
...(more)...
  learn: ekam/rules/test.ekam-rule
...(more)...
...(more)...
  learn: ekam/rules/install.ekam-rule
...(more)...
...(more)...
  learn: ekam/rules/include.ekam-rule
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
  compile: ekam/rules/intercept.c
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
  capnpc: capnp/schema.capnp
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
  capnpc: capnp/rpc-twoparty.capnp
...(more)...
...(more)...
  capnpc: capnp/persistent.capnp
...(more)...
...(more)...
  capnpc: capnp/rpc.capnp
...(more)...
...(more)...
...(more)...
...(more)...
  capnpc: capnp/compiler/grammar.capnp
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
  capnpc: capnp/compiler/lexer.capnp
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
  capnpc: capnp/compat/json.capnp
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
  capnpc: capnp/c++.capnp
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
...(more)...
  learn: ekam/rules/intercept.ekam-rule
terminate called after throwing an instance of 'std::logic_error'
  what():  can't check failures while still running
make: *** [Makefile:33: all] Aborted (core dumped)
builder for '/nix/store/v9g3kpv513mz21qj955n4l6l9sihsnfg-ekam.drv' failed with exit code 2
error: build of '/nix/store/v9g3kpv513mz21qj955n4l6l9sihsnfg-ekam.drv' failed
```

### PR DESCRIPTION
**Pull request by zenhack**
Per discussion on the issue, this is arguably Nix's fault, not ours, but
we should be robust enough that the build doesn't fail just because the
terminal is wonky.

---

I tested this in nix, and can confirm that it prints a warning about a 0 by 0 terminal, and then does simple output.

### CODE REVIEW

File: src/ekam/ekam.cpp [hunk 1]
```diff
@@ -431,6 +433,28 @@ void scanSourceTree(File* src, Driver* driver) {
...
+    return newOwned<SimpleDashboard>(stdout);
+  }
+
+  // Sanity check: make sure the window size is non-zero; otherwise something
+  // is messed up about the terminal, and we should assume it doesn't work
+  // correctly.
+  //
+  // See issue #29
+  struct winsize windowSize;
+  ioctl(STDOUT_FILENO, TIOCGWINSZ, &windowSize);
```
Comment (kentonv) [inline src/ekam/ekam.cpp:447]: Probably should check for errors on this ioctl() call? (Could also fall back to SimpleDashboard in that case.)

**Comment by zenhack** [comment]
> Probably should check for errors on this ioctl() call? (Could also
> fall back to SimpleDashboard in that case.)

Done.

**Comment by kentonv** [comment]
LGTM, thanks!
